server:
  port: 8080

spring:
  application:
    name: products
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge03
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false